id: PF632953B
initial_creation_type: input
source_metadata:
  title: Ajaḍapramātṛsiddhi
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Somadeva Vasudeva
  contribution to GRETIL: Somadeva Vasudeva
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:07:41.099973'
last_modified_at: '2022-03-09T15:07:41.099985'
